### ISSUE TITLE
IMUのサンプルプログラム

### ISSUE THREAD

**Issue by yasuohayashibara** [citbrains/OpenPlatform#10]
IMUの動作確認のため，サンプルプログラムを作成する．
@yoshiya01 pythonでも構いませんので，もしあったらアップして下さい．

**Comment by yoshiya01** [comment]
アップしておきましたmpu-6050.pyです

**Comment by yasuohayashibara** [comment]
動作確認できました．

こちらにあったサンプルも動かしましたが，嫌になるぐらい簡単ですね．
https://www.raspberrypi.org/forums/viewtopic.php?t=22266
とりあえず，こちらのライブラリをそのまま使用したいと思います．

１人で撮影したのと線が細いので良くわからないところもありますが，操作している感覚としては完全に同期しています．
https://youtu.be/0QjVnoqxedI

※ここまで30分．．．

閉じます．

**Comment by yasuohayashibara** [comment]
前回アップした動画がわかりにくかったので取り直しました．
https://youtu.be/DtIKNvIApEQ

ネットが安定していなくて少し停止しているところもあります．
