### ISSUE TITLE
ジャパンオープンでの問題点

### ISSUE THREAD

**Issue by yoshiya01** [citbrains/OpenPlatform#22]
戦略が起動できなくなる
ネットワーク周りのファイルをマージしてコンパイルした辺りから上手く起動出来なくなる
hplのソース再コンパイルで直った
ネットワークが繋げない

デフォルトのWifiが弱すぎる
カメラの画角,高さ(肩などで見れない範囲が多い)
バッテリー過放電させた,やはりアラームが必要
コンパイルが遅すぎる
モーションクリエイターが無い
ポーズイニシャライズが上手く動かない
サーボの値が読めない
リンクパラメータ
チルト角
モーションの再生速度指定が出来ない
HR42等の自動起動
サーボON後出ないとうまくいかない?
rc.localにカメラの情報
LANポートが低すぎる
GPIOスイッチのコード
取手が持ちにくい
取手が緩い
初期値の調整が出来てない?
長穴で逆動作してしまう
トルクリミッター
歩行パラメータ(歩き出し)がオカシイ

**Comment by takayan660** [comment]
腕のサブレーム（COM）がなめる
クロワッシャーの設計変更

**Comment by takayan660** [comment]
csi2のカメラ(OP性を補うため）

**Comment by yasuohayashibara** [comment]
こちら未解決で重要と思われる問題に関しては，別途issueを立ち上げて下さい．

**Comment by yasuohayashibara** [comment]
こちらほぼ対処できたと思いますので，issueを閉じます．
