### ISSUE TITLE
部品発注リスト作成

### ISSUE THREAD

**Issue by yoshiya01** [citbrains/OpenPlatform#24]
Ver.1からVer.2に至るに辺り,既製品の発注リストが不完全になっていました。今後のため発注リストを整理します。

**Comment by yoshiya01** [comment]
ローカルで作業していたものをオンラインで各員が確認できるようにドライブにアップしました。最終的にはリストファイル自体をgitに上げる予定です。https://docs.google.com/spreadsheets/d/1T-6h962NMB8wy8rFKbgDF4RVcZlRBI_5iQs3WqfAVWs/edit?usp=sharing

**Comment by yasuohayashibara** [comment]
１）以下に関して１台分の個数を示して下さい．
LL-7211-08
T6068-4530
D4050-9120B
D3040-7815B
BRU-306_5S
ARU-305_5
ASL-340BE
BRU-305_5

２）以下など，ミスミでエラーになりますので，表記を変更して下さい．
BRU-305_5

305_5 -> 305.5 に変更

**Comment by yasuohayashibara** [comment]
バージョン3に移行しましたので，こちらのissueを閉じます．
