### ISSUE TITLE
入手性の良い広角カメラの検討

### ISSUE THREAD

**Issue by yasuohayashibara** [citbrains/OpenPlatform#26]
以下に入手性の良い広角カメラを見つけた．
https://www.switch-science.com/catalog/3211/

入手性や価格で有利であるため，こちらを採用することを検討する．
ちなみに，TX1にも接続できそうな気がする．
(議論されているのはRaspberry Camera V2ですが，おそらく互換性はあると思います．)
https://devtalk.nvidia.com/default/topic/972364/raspberry-camera-v2-Raspberry Camera-csi-with-jetson-tx1-j100-carrier-board/?offset=6

**Comment by yasuohayashibara** [comment]
１個購入しました．

**Comment by yasuohayashibara** [comment]
カメラ取り付けの様子（両面テープで貼り付けただけです）
![dsc_2752](https://user-images.githubusercontent.com/5755200/33287395-d9c74196-d3fb-11e7-88e1-f26b9da4dcad.jpg)

撮影した画像（足元にボールを置き，カメラを下向きに傾けました．場所はキックオフの位置）
![image](https://user-images.githubusercontent.com/5755200/33287478-23f2347e-d3fc-11e7-984b-3b0d617b42db.png)

最大解像度2592 x 1944でキャプチャした画像の画面をキャプチャしたので，解像度は適当

結果的に，足元のボールもゴールラインのボールも両方視野内に入っている．
おそらく現在使用しているカメラでの画像とそれほど違わないと思われる．

**Comment by yasuohayashibara** [comment]
OpenPlatformではこちらのカメラをまずは採用したいと思いますが，意見がありましたらお願いします．

**Comment by SatoshiShimada** [comment]
ケーブルの取り回しが悪いため実戦投入が心配ですがどのようにお考えでしょうか。

**Comment by yasuohayashibara** [comment]
実験はしていませんが，フラットケーブルの途中を割いてまとめると屈曲に対する耐性が上がるとの情報がありました．

あとは，最悪途中に変換基板を入れて対処することもできると思いますが，こちらが手間が多いですね．
フラットケーブル　→　基板　→　シリコンケーブル　→　基板　→　フラットケーブル

ちなみに，何もせずそのままで市販しているロボットもあります．
http://www.botmag.com/raspberry-pi-camera-robot/

**Comment by SatoshiShimada** [comment]
割いて使用するのは信頼性が薄いので不安が残ります。
基盤を途中にいれるのは良いアイデアだと思いますが、あまり新規開発の案件を増やしたくないため、より一般的なUSBカメラでもよいのではないでしょうか。
#29 でチルト軸を扱うようになっているので広角カメラである必要もないのではないかと考えます。

**Comment by yasuohayashibara** [comment]
意見ありがとう．
多方面からの意見がシステムの完成度を上げると思いますので，議論していきましょう．

基板にMIPI CSI-2のコネクタがあるので，試してみたいというのが一番ですが，実際にどちらが良いかは動かしてみて判断するのでも良いかと思います．
ケーブルに関しては，あまり検証はできていませんが，割かなくても動作することは動作します．
まずは，問題が発生するまで動かすことが重要かなと考えています．

USBに関してですが，複数のデバイスから多くのデータを流すとシステムが実時間で動かなくなることを経験していますので，その点でMIPIを採用した時にどのような変化があるかというのを検証したいと考えています．
実はこの件で一番影響を受けるのは歩行の安定性ではないかと考えています．

広角カメラに関してですが，狭角のカメラを当初は採用することを考えていましたが，現在の画像処理および戦略の開発リソースを見る限り，チルトも含めた画像処理システムを作り直すことは難しいと思いますので，まずは現在のカメラと同じ広角カメラで構成したほうが良いと考えています．

とにかく作って動かしてデータを取ることが必要だと考えています．

**Comment by SatoshiShimada** [comment]
ありがとうございます。確かに安定して動作するなら採用したいですしそのためにも試しておくべきですね。

**Comment by yasuohayashibara** [comment]
議論が一度収束したので，issueを閉じます．
再度議論する必要があれば，オープンします．
