### ISSUE TITLE
腕の長さの検討

### ISSUE THREAD

**Issue by yasuohayashibara** [citbrains/OpenPlatform#28]
腕の長さが足りないために起き上がりをしづらい．
適正な腕の長さを求める．

**Comment by yasuohayashibara** [comment]
現在の腕の長さ
![image](https://user-images.githubusercontent.com/5755200/32987569-c1f5e236-cd32-11e7-8d83-b98fecacfa72.png)

おそらく腕の長さを制限するロボカップのルールは以下となる．
• The robot does not possess a conﬁguration where it is extended longer than 1.5·Htop .

身長　　　608mm
腕の長さ　246.5mm
肩幅　　　183mm
で，(608 * 1.5 - 183 - 2 * 246.5) / 2 = 118

片腕118mm延長してもルール上は問題ない．

**Comment by yasuohayashibara** [comment]
一方起き上がりに必要な腕の長さの検討
60mm程度伸ばせば起き上がりできると考える．

![image](https://user-images.githubusercontent.com/5755200/32987587-798801e0-cd33-11e7-8aa6-84db0b5d4871.png)

![image](https://user-images.githubusercontent.com/5755200/32987588-7c6126bc-cd33-11e7-91a1-c8392433671d.png)

**Comment by yasuohayashibara** [comment]
肩から肘までを40mm，肘から手先までを30mm伸ばして，合計70mm伸ばしたときの様子

![image](https://user-images.githubusercontent.com/5755200/32987614-3631a8a0-cd34-11e7-904c-49782ca4b181.png)

この程度の長さの余裕があれば，問題なく起き上がりできると考える．

**Comment by yasuohayashibara** [comment]
検討してみました．
抜けがあればご指摘ください．

**Comment by yasuohayashibara** [comment]
直立したときの外観は以下のようになる．
（腕をまっすぐ伸ばすと干渉します．）

![image](https://user-images.githubusercontent.com/5755200/32987703-698dd550-cd36-11e7-9cdb-5dc3f90ffb53.png)

**Comment by takayan660** [comment]
少し議論内容から離れているような気がしますが、今の腕先ですと芝生に引っかかる可能性があり、それですと起き上がりに支障をきたすおそれがあるので、3号機のように腕先の面積を増やし丸めた方が良いかと思われます。

写真は3号機の腕先です。
![dsc_2372](https://user-images.githubusercontent.com/12108032/32991900-49b59712-cd87-11e7-9dd5-8b8953b637e8.jpg)

**Comment by yasuohayashibara** [comment]
特に問題を指摘されませんでしたので，こちらのissueを閉じます．
腕を長くする方向で改良を行います．
