### ISSUE TITLE
Gankenkunの破損報告

### ISSUE THREAD

**Issue by takayan660** [citbrains/OpenPlatform#31]
Gankenkunのモーションを作成しようとしたところハードウェアの破損を見つけたので報告します。

* 膝部分でガラスエポキシのリンクが干渉している
 干渉していることにより手で回転させると他より大きな抵抗を感じます。
 左右両足で内側, 外側の計4箇所で発生しています。
![dsc_0524](https://user-images.githubusercontent.com/12107712/32403391-9d2f193a-c17b-11e7-84b0-26140bf3770b.JPG)

* 股のロール軸サーボ周り
  * サーボの出力軸と反対側の軸が板金と干渉している
![dsc_0515](https://user-images.githubusercontent.com/12107712/32403396-c67921dc-c17b-11e7-9ced-6d9a8509ae68.JPG)
  * サーボの出力軸側の面に固定されている板金の破損
![dsc_0522](https://user-images.githubusercontent.com/12107712/32403403-f12475c6-c17b-11e7-9f77-207dcfb67221.JPG)
![dsc_0519](https://user-images.githubusercontent.com/12107712/32403405-f859780a-c17b-11e7-9be5-df4f37f488a1.JPG)

**Comment by takayan660** [comment]
>・膝部分でガラスエポキシのリンクが干渉している
>3DCAD図
>![image](https://user-images.githubusercontent.com/5755200/32978539-8e267d90-cc87-11e7-8fc8-60698fc4aeba.png)
>設計ではわずかながらギャップがあります．
>加工精度の問題だと思われます．

>・股のロール軸サーボ周り
>3DCAD図
>![image](https://user-images.githubusercontent.com/5755200/32978524-29b9dba4-cc87-11e7-88b1-71d7019f51ee.png)

>図面ではギャップがあります．先ほど確認したら部品（ワッシャ）が不足していました．


>サーボの出力軸側の面に固定されている板金の破損

>近くてピントが合わないですが，ネジが長いため板金に無理な力がかかっています．
>![dsc_2654](https://user-images.githubusercontent.com/5755200/32978681-812ab61c-cc8a-11e7-9d82-5a6183e2deb2.jpg)

>頑健君はわりと組み立てがシビアで特定の箇所に特定の部品を使わないと組み立てられませんのでご注意下さい．

**Comment by takayan660** [comment]
>ガラエポの問題について対応しました.すべての箇所図のように削りました.
>![2017-11-18 20 04 24](https://user-images.githubusercontent.com/29033620/32979884-78c9e946-cca0-11e7-9f62-f85efcee6680.jpg)

**Comment by SatoshiShimada** [comment]
https://github.com/citbrains/citbrains_humanoid/issues/816 こちらで議論したものを引継いでいます。
以降はこちらで議論しましょう。

**Comment by shutotakano** [comment]
股のロール軸サーボ周りについて
不足していたワッシャーを加えました.
間隔があいたことを確認しました.
![2017-11-27 14 33 46](https://user-images.githubusercontent.com/29033620/33252600-7d68512a-d382-11e7-9b81-051089c001fe.jpg)

**Comment by yasuohayashibara** [comment]
問題の確認と対策ができたと思われますので，こちらのissueを閉じます．

**Comment by shutotakano** [comment]
13番サーボ(1170-A)がしゃがんている状態で180°命令をして発熱,破損.
長穴機構のネジが緩み,ガラエポと干渉,サーボが大きな抵抗を受け発熱,破損.
写真は後者の破損のものです.
![s_7905696928597](https://user-images.githubusercontent.com/29033620/39659922-cb7bd058-506e-11e8-9155-95d88b0e3ff3.jpg)
![s_7905807884882](https://user-images.githubusercontent.com/29033620/39659924-d1070aba-506e-11e8-90ea-7183dc3b38d6.jpg)
