### ISSUE TITLE
無線LANがつながらない

### ISSUE THREAD

**Issue by yasuohayashibara** [citbrains/OpenPlatform#5]
WIKIに書いた設定を行っても無線LANが接続されない．
sudo iwlist wlan0 scan
ではアドレスが表示されるが，GUIで接続しようとしても接続できない．
手順を再度確認する．

**Comment by ryuichiueda** [comment]
ラズパイ3でしょうか？Wikiまで追っかけられないんですけど、ラズパイの場合だと色々気をつけることがあります。

**Comment by yasuohayashibara** [comment]
ラズパイ３です．
networkmanagerを入れると無線LANに繋がりましたが，動きが全体に緩慢になったような気がします．
（気がするだけかもしれませんが．．．）
ちなみに，VNCで操作しています．
あとで相談させて下さい．

**Comment by ryuichiueda** [comment]
承知しました。ここらへんはノウハウの塊です。

緩慢になるのも理由がありまして・・・

**Comment by yasuohayashibara** [comment]
後でwikiにまとめようかと思いますが，繋がりました．
自宅がまだWEPでしたので，それも問題を複雑にしていたかもしれません．

-----
WIFIの設定
http://qiita.com/yosi-q/items/c677e4650b22ffffa806

WEPの設定
http://nlogn.ath.cx/archives/001378.html

interfacesに以下を追加
wireless-power off

-----
解決したので閉じます．

**Comment by yasuohayashibara** [comment]
そういえばnetwork-managerをapt-get removeしたら動きが早くなりました．
Jessieにnetworkmanagerは相性が悪いようです．
